// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChP89sWkZ3E3uPzUu7vdMBrp4xUxKW7f8',
    appId: '1:530178403011:web:194109198255aeceefd076',
    messagingSenderId: '530178403011',
    projectId: 'pkart-397c5',
    authDomain: 'pkart-397c5.firebaseapp.com',
    storageBucket: 'pkart-397c5.appspot.com',
    measurementId: 'G-FGF844XER7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04IG8TbucYChuTz4qCQwN-wSYqb0pNHA',
    appId: '1:530178403011:android:ab525857bb3d703befd076',
    messagingSenderId: '530178403011',
    projectId: 'pkart-397c5',
    storageBucket: 'pkart-397c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2AuW04X8krNUyG1qlYUmkmbNIJMURNs',
    appId: '1:530178403011:ios:9ec4bcc6acc6ab81efd076',
    messagingSenderId: '530178403011',
    projectId: 'pkart-397c5',
    storageBucket: 'pkart-397c5.appspot.com',
    iosBundleId: 'com.main.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2AuW04X8krNUyG1qlYUmkmbNIJMURNs',
    appId: '1:530178403011:ios:9ec4bcc6acc6ab81efd076',
    messagingSenderId: '530178403011',
    projectId: 'pkart-397c5',
    storageBucket: 'pkart-397c5.appspot.com',
    iosBundleId: 'com.main.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChP89sWkZ3E3uPzUu7vdMBrp4xUxKW7f8',
    appId: '1:530178403011:web:5ee373b0bce6ef0aefd076',
    messagingSenderId: '530178403011',
    projectId: 'pkart-397c5',
    authDomain: 'pkart-397c5.firebaseapp.com',
    storageBucket: 'pkart-397c5.appspot.com',
    measurementId: 'G-JHYRLX5Y7F',
  );
}
